
# ─────────────────────────────────────────
# KLOR — ZMK Config
# ─────────────────────────────────────────

# Keyboard name (shows up when pairing via BT)
CONFIG_ZMK_KEYBOARD_NAME="KLOR"

# ── ZMK Studio ────────────────────────────
# Enables runtime keymap editing via zmk.studio
# CONFIG_ZMK_STUDIO=y

# ── Bluetooth ─────────────────────────────
CONFIG_BT_MAX_PAIRED=5
CONFIG_BT_MAX_CONN=5

# ── Power management ──────────────────────
# Go to sleep after 15 minutes of inactivity
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=400000

# ── RGB underglow ─────────────────────────
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=

CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400